In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
file = pd.read_csv("opaque_index.csv",index_col=0)

In [12]:
file.loc[List[0]]

KeyError: 0

      INVE
0     ELON
1     PEGA
2     PRCP
3     CASS
4     COHU
5     BBOX
6      BDR
7     CRTN
8     HMNY
9    BELFB
10    CDNS
11    KLAC
12      CY
13    XLNX
14    ZOOM
15    TACT
16    WGNR
17    NVDA
18    CMTL
19     AXE
20    TTWO
21     KEM
22    EVOL
23    TKLC
24    ESIO
25      IT
26    MSCC
27    INTC
28    ANEN
29   AMSWA
..     ...
169   AEIS
170   ENVE
171    TCX
172   EGHT
173   COVR
174    AMD
175   ACCL
176   MCRL
177    WDC
178   OSIS
179   CREE
180   SNDK
181   PFSW
182   EDGW
183   ATEA
184   KLIC
185    NCR
186   CNXN
187    IDT
188    AVX
189   ISIL
190    LGL
191   FEIM
192   ATNI
193   QADA
194   TRMB
195   DTLK
196   PCMI
197   CTSH
198   VIAV

[199 rows x 1 columns]

In [13]:
List = pd.read_fwf('DemoList.txt')

In [16]:
text=pd.DataFrame()
for name in List.values.tolist():
    try:
        text=pd.concat([text,file.loc[name]])
    except:
        continue

In [21]:
text

            time    opaque
ELON  12/31/2000  0.084109
ELON   3/31/2001  0.076997
ELON   6/30/2001  0.066354
ELON   9/30/2001  0.058035
ELON  12/31/2001  0.063293
ELON   3/31/2002  0.065486
ELON   6/30/2002  0.064256
ELON   9/30/2002  0.063635
ELON  12/31/2002  0.067651
ELON   3/31/2003  0.066179
ELON   6/30/2003  0.058845
ELON   9/30/2003  0.051246
ELON  12/31/2003  0.053618
ELON   3/31/2004  0.052991
ELON   6/30/2004  0.050903
ELON   9/30/2004  0.045498
ELON  12/31/2004  0.033580
ELON   3/31/2005  0.031384
ELON   6/30/2005  0.032688
ELON   9/30/2005  0.037620
ELON  12/31/2005  0.034997
ELON   3/31/2006  0.034598
ELON   6/30/2006  0.032328
ELON   9/30/2006  0.026598
ELON  12/31/2006  0.020453
ELON   3/31/2007  0.022125
ELON   6/30/2007  0.022325
ELON   9/30/2007  0.023829
ELON  12/31/2007  0.024947
ELON   3/31/2008  0.024158
...          ...       ...
VIAV  12/31/2011  0.101331
VIAV   3/31/2012  0.065280
VIAV   6/30/2012  0.024066
VIAV   9/30/2012  0.025114
VIAV  12/31/2012  0.023777
VIAV   3/31/2013  0.023474
VIAV   6/30/2013  0.019462
VIAV   9/30/2013  0.020559
VIAV  12/31/2013  0.021487
VIAV   3/31/2014  0.020965
VIAV   6/30/2014  0.022304
VIAV   9/30/2014  0.021809
VIAV  12/31/2014  0.021609
VIAV   3/31/2015  0.022698
VIAV   6/30/2015  0.021473
VIAV   9/30/2015  0.019482
VIAV  12/31/2015  0.019623
VIAV   3/31/2016  0.017323
VIAV   6/30/2016  0.020350
VIAV   9/30/2016  0.023049
VIAV  12/31/2016  0.028886
VIAV   3/31/2017  0.036782
VIAV   6/30/2017  0.039865
VIAV   9/30/2017  0.038612
VIAV  12/31/2017  0.038165
VIAV   3/31/2018  0.037155
VIAV   6/30/2018  0.037186
VIAV   9/30/2018  0.038054
VIAV  12/31/2018  0.037940
VIAV   3/31/2019  0.039248

[13214 rows x 2 columns]